[package]
name = "eth2_ssz_types"
version = "0.2.2"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2021"
description = "Provides types with unique properties required for SSZ serialization and Merklization."
license = "Apache-2.0"

[lib]
name = "ssz_types"

[dependencies]
tree_hash = { path = "../tree_hash", default-features = false }
serde = { version = "1.0.116", default-features = false }
serde_derive = "1.0.116"
eth2_serde_utils = { path = "../serde_utils", default-features = false }
eth2_ssz = { path = "../ssz", default-features = false }
typenum = "1.12.0"
# arbitrary didn't support no-std
arbitrary = { version = "1.0", features = ["derive"], optional = true }
# derivative enable feature "use_core" for "no-std"
derivative = { version = "2.1.1", features = ["use_core"] }
smallvec = "1.8.0"

[dev-dependencies]
serde_json = "1.0.58"
tree_hash_derive = { path = "../tree_hash_derive" }

[features]
default = ["std"]
std = ["tree_hash/std", "serde/std", "eth2_serde_utils/std", "eth2_ssz/std", "arbitrary"]
